### PR TITLE
64 bit rebased

### PR DESCRIPTION
**Pull request by bluewww**
* Ignore most changes on master and prefer this branch
* Changes that removed clock gating stuff happened in both master and this branch
* Squash jg stuff

### CODE REVIEW

**Comment by bluewww** [comment]
@accuminium can you have a look at this and merge if no objections?

**Review by andreaskurth — APPROVED** [review]
If this works for the use cases in PULP SoCs it was developed for, it is fine for me.  Did you check that?

**Comment by bluewww** [comment]
Yes. It works for PULPissimo and PULP.

**Comment by andreaskurth** [comment]
Thanks for your work!

**Pull request merged**
